name: Publish Docker
on: [push]
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
    - name: Build container
      run: docker build --no-cache -t ${GITHUB_REPOSITORY}:${GITHUB_SHA} .

    - name: Run container
      run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ${GITHUB_REPOSITORY}:${GITHUB_SHA}

  push_to_hub:
    needs: build_and_run
    steps:
    - name: Push container to docker hub
      run: |
      echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      docker push ${GITHUB_REPOSITORY}:${GITHUB_SHA}
